FROM registry.access.redhat.com/rhscl/mariadb-102-rhel7

USER 0
COPY database.sql /opt/app-root/src
COPY .podman/mariadb-load-db.sh /opt/app-root/src
RUN chown -R 1001:0 /opt/app-root/src
USER 1001

CMD /usr/libexec/s2i/run
