---
- name: Start RTI
  hosts: all
  connection: local
  tasks:
    - name: Create a podman network for rti
      containers.podman.podman_network:
        name: rti

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: Containerfile-rtidb
        dest: ../Containerfile

    - name: Build RTIdb
      containers.podman.podman_image:
        name: rtidb
        path: ../
        force: true

    - name: Remove rtidb Containerfile
      ansible.builtin.file:
        path: ../Containerfile
        state: absent

    - name: Start RTIdb
      containers.podman.podman_container:
        name: rtidb
        image: rtidb
        network: rti
        state: started
        restart_policy: unless-stopped
        env:
          MYSQL_USER=dbuser
          MYSQL_PASSWORD=dbpass
          MYSQL_DATABASE=dbrti

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: Containerfile-rti
        dest: ../Containerfile

    - name: Build RTI
      containers.podman.podman_image:
        name: rti
        path: ../
        force: true

    - name: Remove rti Containerfile
      ansible.builtin.file:
        path: ../Containerfile
        state: absent

    - name: Start RTI
      containers.podman.podman_container:
        name: rti
        image: rti
        network: rti
        state: started
        recreate: true
        restart_policy: unless-stopped
        ports: 
          - 8080:8080
        env:
          MYSQL_SVC=rtidb
          MYSQL_USER=dbuser
          MYSQL_PASSWORD=dbpass
          MYSQL_DATABASE=dbrti
